---
title: "Rethinking Stats Chapter 12.Rmd"
author: "Alex Bayers"
date: "04/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Easy

### Problem 1

Prior a) will produce more shrinkage, as the lower standard deviation forces each a(tank) closer to 0.

### Problem 2
$$
\\y_i \sim  Binomial(1, p_i)
\\logit(p_i) \sim \alpha_{GROUP[i]} \> + \> \beta x_i
\\\alpha_{GROUP} \sim Normal(\alpha, \>\sigma)
\\\alpha \sim Normal(0, 10)
\\\beta \sim Normal(0, 1)
\\\sigma \sim HalfCauchy(0, 1)
$$

### Problem 3
$$
\\y_i \sim  Normal(\mu_i, \sigma)
\\\mu_i \sim \alpha_{GROUP[i]} \> + \> \beta x_i
\\\alpha_{GROUP} \sim Normal(\alpha, \>\epsilon)
\\\alpha \sim Normal(0, 10)
\\\beta \sim Normal(0, 1)
\\\sigma \sim HalfCauchy(0, 2)
\\\epsilon \sim HalfCauchy(0, 2)
$$

### Problem 4
$$
\\T_i \sim Poisson(\mu_i)
\\log(u_i) \sim \alpha + \alpha_{SOCIETY_{[i]}} + \beta_P * log \> P_i
\\\alpha \sim Normal(0, 10)
\\\beta_P \sim Normal(0, 1)
\\\alpha_{SOCIETY} \sim Normal(0, \sigma_{SOCIETY})
\\\sigma_{SOCIETY} \sim HalfCauchy(0,1)
$$

# Medium
### Problem 1
```{r}
library(rethinking)
data(reedfrogs)
d <- reedfrogs
d$tank <- 1:nrow(d)

m12.1 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank],
    a_tank[tank]  ~ dnorm(0, 5)
  ),
  data = d
)

precis(m12.1, depth = 2)
```

```{r}
m12.2 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank],
    a_tank[tank]  ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1)
  ),
  data = d,
  iter = 4000,
  chains = 4
)

precis(m12.2, depth = 2)
```

```{r}
compare(m12.1, m12.2)
```

```{r}
#extract STAN samples
post <- extract.samples(m12.2)

d$propsurv.est <- logistic(apply(post$a_tank, 2, median))

#display raw proportions
plot(d$propsurv, ylim = c(0, 1), pch = 16, xaxt = "n", xlab = "tank", ylab= "proportion survival", col = rangi2)
axis(1, at = c(1, 16, 32, 48), labels = c(1, 16, 32, 48))

#overlay posterior medians
points(d$propsurv.est)

#mark posterior median probability across tanks
abline(h=logistic(median(post$a)), lty = 2)

#draw vertical dividers
abline(v=16.5, lwd = 0.5)
abline(v=32.5, lwd = 0.5)
text(8, 0, "small tanks")
text(16+8, 0, "medium tanks")
text(32+8, 0, "large tanks")
```


```{r}
d$predbool <- ifelse(d$pred == "pred", 1, 0)
m12.3 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank] + bp*predbool,
    a_tank[tank]  ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1),
    bp ~ dnorm(0, 10)
  ),
  data = d,
  iter = 4000,
  chains = 4
)

precis(m12.3, depth = 2)

```

```{r}
#Now ordered logit
d$large = ifelse(d$size=="large", 1, 0)
d$medium = ifelse(d$size=="medium", 1, 0)

m12.4 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank] +  bl*large + bm*medium,
    a_tank[tank]  ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1),
    bp ~ dnorm(0, 10),
    bl ~ dnorm(0, 10),
    bm ~ dnorm(0, 10)
  ),
  data = d,
  iter = 4000,
  chains = 4
)

precis(m12.4, depth = 2)

```


```{r}
#Now ordered logit
d$large = ifelse(d$size=="large", 1, 0)
d$medium = ifelse(d$size=="medium", 1, 0)

m12.5 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank] + bp*predbool + bl*large + bm*medium,
    a_tank[tank]  ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1),
    bp ~ dnorm(0, 3),
    bl ~ dnorm(0, 3),
    bm ~ dnorm(0, 3)
  ),
  data = d,
  iter = 4000,
  chains = 4
)

precis(m12.5, depth = 2)
```

```{r}
#Now interactions
m12.6 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank] + bp*predbool + bl*large + bm*medium + bpl*predbool*large + bpm*predbool*medium,
    a_tank[tank]  ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1),
    bp ~ dnorm(0, 10),
    bl ~ dnorm(0, 3),
    bm ~ dnorm(0, 3),
    bpl ~ dnorm(0, 3),
    bpm ~ dnorm(0, 3)
  ),
  data = d,
  iter = 4000,
  chains = 4
)

precis(m12.6, depth = 2)
```


```{r}
compare(m12.1, m12.2, m12.3, m12.4, m12.5, m12.6)
coeftab(m12.3, m12.5, m12.6, se = TRUE)
```

So we get an equal loading on the predation and 